# Generated by Django 5.2.1 on 2025-05-17 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название направления')),
                ('code', models.CharField(max_length=50, verbose_name='Код направления')),
                ('faculty', models.CharField(max_length=255, verbose_name='Факультет')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название предмета')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='PassingScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год')),
                ('score', models.PositiveSmallIntegerField(verbose_name='Проходной балл')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passing_scores', to='mainpage.specialty', verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Проходной балл',
                'verbose_name_plural': 'Проходные баллы',
                'unique_together': {('direction', 'year')},
            },
        ),
        migrations.CreateModel(
            name='DirectionSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.BooleanField(default=False, help_text='Отметьте для обязательных предметов (например, математика и русский)', verbose_name='Обязательный предмет')),
                ('min_points', models.PositiveSmallIntegerField(verbose_name='Минимальный балл')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_subjects', to='mainpage.specialty', verbose_name='Направление')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Предмет направления',
                'verbose_name_plural': 'Предметы направлений',
                'unique_together': {('direction', 'subject')},
            },
        ),
    ]
