# Generated by Django 5.2.1 on 2025-06-01 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год')),
                ('score', models.PositiveSmallIntegerField(verbose_name='Проходной балл')),
                ('number_of_places', models.PositiveSmallIntegerField(verbose_name='Количество мест')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_stats', to='mainpage.specialty', verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Проходной балл',
                'verbose_name_plural': 'Проходные баллы',
                'unique_together': {('direction', 'year')},
            },
        ),
        migrations.DeleteModel(
            name='PassingScore',
        ),
    ]
