# Generated by Django 5.2.1 on 2025-06-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_admissionstats_delete_passingscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='url',
            field=models.CharField(default=1, max_length=255, verbose_name='url адрес направления'),
            preserve_default=False,
        ),
    ]
