# Generated by Django 5.2.1 on 2025-06-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_alter_specialty_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialty',
            name='url',
            field=models.CharField(blank='True', max_length=500, null='True', verbose_name='url адрес направления'),
        ),
    ]
