# Generated by Django 5.2.1 on 2025-06-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0007_alter_specialty_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialty',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL страницы специальности'),
        ),
    ]
