# Generated by Django 5.2.1 on 2025-06-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0008_alter_specialty_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admissionstats',
            options={'verbose_name': 'Средний балл', 'verbose_name_plural': 'Средние баллы'},
        ),
        migrations.AlterField(
            model_name='admissionstats',
            name='score',
            field=models.PositiveSmallIntegerField(verbose_name='Средний балл'),
        ),
    ]
